# Generated by Django 6.0.3 on 2026-03-08 00:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'année scolaire',
                'verbose_name_plural': 'années scolaires',
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('niveau', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'classe',
                'verbose_name_plural': 'classes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(editable=False, help_text="Généré automatiquement à l'enregistrement", max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('telephone_parent', models.CharField(blank=True, max_length=30)),
                ('email_parent', models.EmailField(blank=True, max_length=254)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eleves', to='gestion.anneescolaire')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eleves', to='gestion.classe')),
            ],
            options={
                'verbose_name': 'élève',
                'verbose_name_plural': 'élèves',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='FraisScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('obligatoire', models.BooleanField(default=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais', to='gestion.anneescolaire')),
            ],
            options={
                'verbose_name': 'frais scolaire',
                'verbose_name_plural': 'frais scolaires',
                'ordering': ['annee_scolaire__nom', 'libelle'],
                'unique_together': {('annee_scolaire', 'libelle')},
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('coefficient', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('classe', models.ForeignKey(help_text='Classe principale pour cette matière', on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='gestion.classe')),
            ],
            options={
                'verbose_name': 'matière',
                'verbose_name_plural': 'matières',
                'ordering': ['classe__nom', 'nom'],
                'unique_together': {('nom', 'classe')},
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('matieres', models.ManyToManyField(blank=True, related_name='enseignants', to='gestion.matiere')),
            ],
            options={
                'verbose_name': 'enseignant',
                'verbose_name_plural': 'enseignants',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField(default=django.utils.timezone.now)),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode', models.CharField(choices=[('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile money'), ('VIREMENT', 'Virement bancaire'), ('CHEQUE', 'Chèque')], default='ESPECES', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Référence du reçu / transaction', max_length=100)),
                ('remarque', models.CharField(blank=True, max_length=255)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='gestion.eleve')),
                ('frais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='gestion.fraisscolaire')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('ordre', models.PositiveIntegerField(help_text="Ordre d'affichage (1, 2, ...)")),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestres', to='gestion.anneescolaire')),
            ],
            options={
                'verbose_name': 'semestre',
                'verbose_name_plural': 'semestres',
                'ordering': ['annee_scolaire__nom', 'ordre'],
                'unique_together': {('annee_scolaire', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('CONTROLE', 'Contrôle'), ('DEVOIR', 'Devoir'), ('EXAMEN', 'Examen')], max_length=20)),
                ('coefficient', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='gestion.matiere')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='gestion.semestre')),
            ],
            options={
                'verbose_name': 'évaluation',
                'verbose_name_plural': 'évaluations',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=5)),
                ('remarque', models.CharField(blank=True, max_length=255)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='gestion.eleve')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='gestion.evaluation')),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
                'unique_together': {('eleve', 'evaluation')},
            },
        ),
    ]
