# Generated by Django 6.0.3 on 2026-03-08 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreEcole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delai_jours_rappel_impayes', models.PositiveIntegerField(default=3, help_text='Nombre de jours après la date limite pour notifier les mensualités impayées.')),
            ],
            options={
                'verbose_name': 'paramètre école',
                'verbose_name_plural': 'paramètres école',
            },
        ),
        migrations.CreateModel(
            name='PeriodeMensuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')])),
                ('annee', models.PositiveIntegerField()),
                ('date_limite', models.DateField(help_text='Date limite de paiement (ex. 5 du mois suivant).')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes_mensuelles', to='gestion.anneescolaire')),
            ],
            options={
                'verbose_name': 'période mensuelle',
                'verbose_name_plural': 'périodes mensuelles',
                'ordering': ['annee_scolaire', 'annee', 'mois'],
                'unique_together': {('annee_scolaire', 'mois', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='ReglementMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paye', models.BooleanField(default=False, verbose_name='Payé')),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglements_mensuels', to='gestion.eleve')),
                ('paiement', models.OneToOneField(blank=True, help_text='Lien optionnel vers le paiement (compta).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglement_mensuel', to='gestion.paiement')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglements', to='gestion.periodemensuelle')),
            ],
            options={
                'verbose_name': 'règlement mensuel',
                'verbose_name_plural': 'règlements mensuels',
                'ordering': ['-periode__annee', '-periode__mois', 'eleve__nom'],
                'unique_together': {('eleve', 'periode')},
            },
        ),
    ]
